tgname|table_name|definition
activities_places_restantes|activities|CREATE TRIGGER activities_places_restantes BEFORE INSERT OR UPDATE ON public.activities FOR EACH ROW EXECUTE FUNCTION update_places_restantes()
activities_updated_at|activities|CREATE TRIGGER activities_updated_at BEFORE UPDATE ON public.activities FOR EACH ROW EXECUTE FUNCTION update_activities_updated_at()
on_activity_cancelled_push|activities|CREATE TRIGGER on_activity_cancelled_push AFTER UPDATE ON public.activities FOR EACH ROW WHEN ((((old.status)::text IS DISTINCT FROM (new.status)::text) AND ((new.status)::text = ANY ((ARRAY['paused'::character varying, 'cancelled'::character varying])::text[])))) EXECUTE FUNCTION notify_participants_on_cancel()
on_activity_deleted_push|activities|CREATE TRIGGER on_activity_deleted_push BEFORE DELETE ON public.activities FOR EACH ROW EXECUTE FUNCTION notify_participants_on_cancel()
enforce_bucket_name_length_trigger|buckets|CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length()
protect_buckets_delete|buckets|CREATE TRIGGER protect_buckets_delete BEFORE DELETE ON storage.buckets FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete()
update_conversations_updated_at|conversations|CREATE TRIGGER update_conversations_updated_at BEFORE UPDATE ON public.conversations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
on_friend_request_insert_push|friend_requests|CREATE TRIGGER on_friend_request_insert_push AFTER INSERT ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION trigger_friend_request_push()
update_friend_requests_updated_at|friend_requests|CREATE TRIGGER update_friend_requests_updated_at BEFORE UPDATE ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
cron_job_cache_invalidate|job|CREATE TRIGGER cron_job_cache_invalidate AFTER INSERT OR DELETE OR UPDATE OR TRUNCATE ON cron.job FOR EACH STATEMENT EXECUTE FUNCTION cron.job_cache_invalidate()
on_message_insert_push|messages|CREATE TRIGGER on_message_insert_push AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION trigger_message_push()
update_conversation_on_new_message|messages|CREATE TRIGGER update_conversation_on_new_message AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION update_conversation_last_message()
update_messages_updated_at|messages|CREATE TRIGGER update_messages_updated_at BEFORE UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
protect_objects_delete|objects|CREATE TRIGGER protect_objects_delete BEFORE DELETE ON storage.objects FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete()
update_objects_updated_at|objects|CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column()
set_updated_at|profiles|CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION handle_updated_at()
reports_updated_at_trigger|reports|CREATE TRIGGER reports_updated_at_trigger BEFORE UPDATE ON public.reports FOR EACH ROW EXECUTE FUNCTION update_reports_updated_at()
reviews_update_business_rating|reviews|CREATE TRIGGER reviews_update_business_rating AFTER INSERT OR DELETE OR UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION trigger_update_business_rating()
trigger_update_business_stats|slot_participants|CREATE TRIGGER trigger_update_business_stats AFTER INSERT ON public.slot_participants FOR EACH ROW EXECUTE FUNCTION update_business_stats()
tr_check_filters|subscription|CREATE TRIGGER tr_check_filters BEFORE INSERT OR UPDATE ON realtime.subscription FOR EACH ROW EXECUTE FUNCTION realtime.subscription_check_filters()
(20 rows)
